#!/bin/bash
FRAMEWORK_NAME="PIPPO"
BUILD_CONFIGURATION="Release"
SCHEME_NAME="Pluto"

echo "NAME: ${FRAMEWORK_NAME}"
echo "CONFIGURATION: ${BUILD_CONFIGURATION}"
echo "SCHEME: ${SCHEME_NAME}"


ARCHIVE_PATH="/xcarchives"
IOS_SIMULATOR_ARCHIVE_PATH="$(pwd)${ARCHIVE_PATH}/${SCHEME_NAME}-iphonesimulator.xcarchive"
IOS_DEVICE_ARCHIVE_PATH="${ARCHIVE_PATH}/${SCHEME_NAME}-iphoneos.xcarchive"
TV_SIMULATOR_ARCHIVE_PATH="${ARCHIVE_PATH}/${SCHEME_NAME}-appletvsimulator.xcarchive"
TV_DEVICE_ARCHIVE_PATH="${ARCHIVE_PATH}/${SCHEME_NAME}-appletvos.xcarchive"
WATCH_SIMULATOR_ARCHIVE_PATH="${ARCHIVE_PATH}/${SCHEME_NAME}-watchsimulator.xcarchive"
WATCH_DEVICE_ARCHIVE_PATH="${ARCHIVE_PATH}/${SCHEME_NAME}-watchos.xcarchive"
MACOS_ARCHIVE_PATH="${ARCHIVE_PATH}/${SCHEME_NAME}-macosx.xcarchive"
CATALYST_ARCHIVE_PATH="${ARCHIVE_PATH}/${SCHEME_NAME}-catalyst.xcarchive"
OUTPUT_FRAMEWORK_PATH="./xcframeworks/"

echo "Path: ${IOS_SIMULATOR_ARCHIVE_PATH}"
echo "$(pwd)"
